 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [08/Jan/2023 11:39:25] "[37mPOST /signup/v1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [08/Jan/2023 11:40:25] "[37mPOST /signup/v1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [08/Jan/2023 11:41:59] "[37mPOST /login/v1 HTTP/1.1[0m" 200 -
127.0.0.1 - - [08/Jan/2023 11:42:47] "[37mPOST /login/v1 HTTP/1.1[0m" 200 -
 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
[2023-01-08 12:54:34,887] ERROR in app: Exception on /signup/v2 [POST]
Traceback (most recent call last):
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "password-evolution.py", line 60, in signup_v2
    conn = sqdlite3.connect (db_name)
NameError: name 'sqdlite3' is not defined
127.0.0.1 - - [08/Jan/2023 12:54:34] "[35m[1mPOST /signup/v2 HTTP/1.1[0m" 500 -
[2023-01-08 12:57:28,261] ERROR in app: Exception on /signup/v2 [POST]
Traceback (most recent call last):
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "password-evolution.py", line 60, in signup_v2
    conn = sqdlite3.connect (db_name)
NameError: name 'sqdlite3' is not defined
127.0.0.1 - - [08/Jan/2023 12:57:28] "[35m[1mPOST /signup/v2 HTTP/1.1[0m" 500 -
[2023-01-08 12:57:44,119] ERROR in app: Exception on /signup/v2 [POST]
Traceback (most recent call last):
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devasc/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "password-evolution.py", line 60, in signup_v2
    conn = sqlite3.connect(db_name)
NameError: name 'sqdlite3' is not defined
127.0.0.1 - - [08/Jan/2023 12:57:44] "[35m[1mPOST /signup/v2 HTTP/1.1[0m" 500 -
 * Serving Flask app "password-evolution" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [08/Jan/2023 13:08:37] "[37mPOST /signup/v2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [08/Jan/2023 13:08:41] "[37mPOST /signup/v2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [08/Jan/2023 13:09:17] "[37mPOST /signup/v2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [08/Jan/2023 13:10:12] "[31m[1mPOST /signup/v2 HTTP/1.1[0m" 400 -
127.0.0.1 - - [08/Jan/2023 13:11:25] "[31m[1mPOST /signup/v2 HTTP/1.1[0m" 400 -
127.0.0.1 - - [08/Jan/2023 13:11:56] "[37mPOST /login/v2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [08/Jan/2023 13:12:17] "[37mPOST /login/v2 HTTP/1.1[0m" 200 -
